pipeline {
    agent any
    environment {
        VENV_DIR = "venv"
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/skkooo27/alx-backend-python.git'
            }
        }
        stage('Setup Python') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
                sh './venv/bin/pip install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest --junitxml=report.xml'
            }
        }
        stage('Archive Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
