pipeline {
    agent any
    environment {
        VENV_DIR = "venv"
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/skkooo27/alx-backend-python.git'
            }
        }
        stage('Setup Python') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
                sh './venv/bin/pip install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest --junitxml=report.xml'
            }
        }
        stage('Archive Report') {
            steps {
                junit 'report.xml'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build Docker image from Dockerfile in messaging_app directory
                sh 'docker build -t skkooo27/messaging-app:latest messaging_app'
            }
        }
        stage('Push Docker Image') {
            steps {
                // Use Docker Hub credentials stored in Jenkins
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push skkooo27/messaging-app:latest
                    '''
                }
            }
        }
    }
}
