#!/bin/bash

# Deploy blue and green versions
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml

# Check pods
echo "Checking running pods..."
kubectl get pods -l app=messaging-app

# Check logs of green deployment (first pod)
GREEN_POD=$(kubectl get pods -l app=messaging-app,version=green -o jsonpath='{.items[0].metadata.name}')
echo "Logs from green deployment pod: $GREEN_POD"
kubectl logs $GREEN_POD
