# Generated by Django 5.2.4 on 2025-07-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='to_user',
        ),
    ]
